export default [
  {
    id: 1,
    slug: 'rev-engg-wifi-router',
    blogFile: '/blog1.md',
    date: '2024-01-15',
    title: 'My Hands-on Reverse Engineering a Router... Everyone is welcome',
  },
  {
    id: 2,
    slug: 'isc2-cc',
    blogFile: '/blog2.md',
    date: '2024-02-10',
    title: 'How to ace your ISC²: Certified in Cybersecurity',
  },
  {
    id: 3,
    slug: 'laptop-upgradation',
    blogFile: '/blog3.md',
    date: '2024-03-10',
    title: 'The Complete Laptop Upgradation Guide',
  },
  {
    id: 4,
    slug: 'aws-cp',
    blogFile: '/blog4.md',
    date: '2024-04-10',
    title: 'How I Cleared My AWS Cloud Practitioner for Almost Free!',
  },
  {
    id: 5,
    slug: 'better-osint',
    blogFile: '/blog5.md',
    date: '2024-12-10',
    title: 'How to be a better OSINTer',
  },
  {
    id: 6,
    slug: 'network-query',
    blogFile: '/blo62.md',
    date: '2024-02-10',
    title: 'Mastering React Hooks: A Complete Guide to Efficient State Management',
  },
    // {
  //   id: 2,
  //   slug: 'mastering-react-hooks',
  //   blogFile: '/blog2.md',
  //   date: '2024-02-10',
  //   title: 'Mastering React Hooks: A Complete Guide to Efficient State Management',
  // },
];
