export default [
  {
    id: 1,
    slug: 'introduction-to-javascript',
    blogFile: '/blog1.md',
    date: '2024-01-15',
    title: 'A Comprehensive Guide to Getting Started with JavaScript for Beginners',
  },
  {
    id: 2,
    slug: 'mastering-react-hooks',
    blogFile: '/blog2.md',
    date: '2024-02-10',
    title: 'Mastering React Hooks: A Complete Guide to Efficient State Management',
  },
  {
    id: 3,
    slug: 'nodejs-best-practices',
    blogFile: '/blog1.md',
    date: '2024-03-05',
    title: 'Node.js Best Practices: Writing Clean and Scalable Backend Code',
  },
  {
    id: 4,
    slug: 'understanding-async-await',
    blogFile: '/blog2.md',
    date: '2024-03-25',
    title: 'Understanding Async/Await: Simplify Asynchronous Programming in JavaScript',
  },
  {
    id: 5,
    slug: 'css-grid-vs-flexbox',
    blogFile: '/blog1.md',
    date: '2024-04-12',
    title: 'CSS Grid vs. Flexbox: Choosing the Right Layout for Your Web Design Needs',
  },
  {
    id: 6,
    slug: 'seo-tips-for-developers',
    blogFile: '/blog2.md',
    date: '2024-05-01',
    title: 'Top SEO Tips for Developers: How to Optimize Your Websites for Search Engines',
  },
  {
    id: 7,
    slug: 'building-restful-apis',
    blogFile: '/blog1.md',
    date: '2024-06-18',
    title: 'Building RESTful APIs: A Step-by-Step Guide for Scalable Backend Systems',
  },
  {
    id: 8,
    slug: 'introduction-to-web3',
    blogFile: '/blog2.md',
    date: '2024-07-08',
    title: 'An Introduction to Web3: Exploring the Future of Decentralized Applications',
  },
  {
    id: 9,
    slug: 'debugging-in-chrome-devtools',
    blogFile: '/blog1.md',
    date: '2024-08-20',
    title: 'Debugging Made Easy: A Developer’s Guide to Using Chrome DevTools Effectively',
  },
  {
    id: 10,
    slug: 'writing-efficient-sql-queries',
    blogFile: '/blog2.md',
    date: '2024-09-14',
    title: 'Writing Efficient SQL Queries: Techniques to Optimize Database Performance',
  },
];
